# Generated by Django 2.2.7 on 2019-11-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('url_link', models.CharField(max_length=512)),
            ],
        ),
    ]
