# Generated by Django 2.2.7 on 2019-11-09 11:47

from django.db import migrations, models
import url.validators


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='url_link',
            field=models.CharField(max_length=512, validators=[url.validators.validate_link]),
        ),
    ]
