# Generated by Django 2.2.7 on 2019-11-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_auto_20191109_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortedLinks',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('url_shorted_link', models.CharField(max_length=512)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url.Links')),
            ],
        ),
    ]
