# Generated by Django 2.2.7 on 2019-11-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_shortedlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='url_shorted_link',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ShortedLinks',
        ),
    ]
