# Generated by Django 2.2.7 on 2019-11-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0004_auto_20191109_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Short_cut',
            fields=[
                ('shortcut', models.CharField(max_length=6, primary_key=True, serialize=False)),
            ],
        ),
    ]
