# Generated by Django 2.2.7 on 2019-11-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0005_short_cut'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Short_cut',
            new_name='Shortcut',
        ),
    ]
